#pragma once
#include "ButtonObject.h"
#include "RectangleObject.h"
#include "TextObject.h"
#include "CanvasObject.h"
#include "LineObject.h"
#include "ProgressObject.h"
#include "InputObject.h"
#include "ImageObject.h"